#! /bin/bash

With time am going to be the best. All i need is time, and dedication. The motor is that nothing is impossible.


So help me God

And now am learning on azure how to become a devops engineer and get a job to better the life of my family
